# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="eac285e4-83ac-405a-8f0e-bbc7d5c0baeb"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - selesitomorozov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always